# Generated by Django 4.1 on 2022-09-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_usermodel_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='type',
        ),
        migrations.AlterField(
            model_name='evalutionmodel',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
        migrations.AlterField(
            model_name='inquirymodel',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='SportsName',
            field=models.CharField(choices=[('Cricket', 'Cricket'), ('Volleyball', 'Volleyball'), ('Football', 'Football'), ('Basketball', 'Basketball'), ('Badminton', 'Badminton')], default='cricket', max_length=50),
        ),
        migrations.AlterField(
            model_name='tournamentmodel',
            name='Dept',
            field=models.CharField(choices=[('LJMCA', 'LJMCA'), ('LJMBA', 'LJMBA')], default='LJMCA', max_length=50),
        ),
        migrations.AlterField(
            model_name='tournamentmodel',
            name='SportsName',
            field=models.CharField(choices=[('Cricket', 'Cricket'), ('Volleyball', 'Volleyball'), ('Football', 'Football'), ('Basketball', 'Basketball'), ('Badminton', 'Badminton')], default='cricket', max_length=50),
        ),
    ]
