# Generated by Django 4.1 on 2022-09-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_usermodel_type_alter_evalutionmodel_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='roomserviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SUPER_DELUXE', 'SUPER_DELUXE'), ('SEMI_SUITE', 'SEMI_SUITE'), ('EXECUTIVE_DELXUE', 'EXECUTIVE_DELXUE'), ('SUITE_ROOM', 'SUITE_ROOM')], default='SUPER_DELUXE', max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
