# Generated by Django 4.1 on 2022-09-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_roomservicemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='messageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Members', 'Members'), ('Childrens', 'Childrens'), ('Adults', 'Adults')], default='Members', max_length=200)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
