# Generated by Django 4.1 on 2022-09-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_cricketmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='footballModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameoftournament', models.CharField(choices=[('DURAND_CUP', 'DURAND_CUP'), ('IFA_SHIELD', 'IFA_SHIELD'), ('SUBROTO_CLUB', 'SUBROTO_CLUB'), ('SANTOSH_TROPHY', 'SANTOSH_TROPHY'), ('ISL', 'ISL')], default='ISL', max_length=200)),
                ('criteriaofage', models.CharField(choices=[('UNDER_19', 'UNDER_19'), ('UNDER_13', 'UNDER_13'), ('UNDER_21', 'UNDER_21')], default='UNDER_19', max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('dept', models.CharField(choices=[('LJMCA', 'LJMCA'), ('LJMBA', 'LJMBA')], default='LJMCA', max_length=50)),
            ],
        ),
    ]
