# Generated by Django 4.1 on 2022-09-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_basketballmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='karateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameoftournament', models.CharField(choices=[('SPORT_KARATE_INTERNATIONAL', 'SPORT_KARATE_INTERNATIONAL'), ('NATIONAL_BLACK_BELT_LEAGUE', 'NATIONAL_BLACK_BELT_LEAGUE'), ('PROFESSIONAL_POINT_KARATE_FEDERAATION', 'PROFESSIONAL_POINT_KARATE_FEDERAATION'), ('UNIVERSAL_MARTIAL_ARTS_ASSOCIATE', 'UNIVERSAL_MARTIAL_ARTS_ASSOCIATE'), ('NORTH_AMERICA_SPORT_KARATE_ASSOCIATION', 'NORTH_AMERICA_SPORT_KARATE_ASSOCIATION')], default='ASIAN_CHAMPIONSHIPS', max_length=200)),
                ('criteriaofage', models.CharField(choices=[('UNDER_19', 'UNDER_19'), ('UNDER_13', 'UNDER_13'), ('UNDER_21', 'UNDER_21')], default='UNDER_19', max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('dept', models.CharField(choices=[('LJMCA', 'LJMCA'), ('LJMBA', 'LJMBA')], default='LJMCA', max_length=50)),
            ],
        ),
    ]
