# Generated by Django 4.1 on 2022-09-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_weightliftingmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='volleyballModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameoftournament', models.CharField(choices=[('FEDERATION_CUP', 'FEDERATION_CUP'), ('NATIONAL_VOLLEYBALL_CHAMPIONSHIP', 'NATIONAL_VOLLEYBALL_CHAMPIONSHIP'), ('BEACH_VOLLEYBALL', 'BEACH_VOLLEYBALL'), ('PRO_VOLLEYBALL_LEAGUE', 'PRO_VOLLEYBALL_LEAGUE'), ('SUB_JUNIOR_NATIONAL_VOLLEYBALL_CHAMPIONSHIP', 'SUB_JUNIOR_NATIONAL_VOLLEYBALL_CHAMPIONSHIP')], default='FEDERATION_CUP', max_length=200)),
                ('criteriaofage', models.CharField(choices=[('UNDER_19', 'UNDER_19'), ('UNDER_13', 'UNDER_13'), ('UNDER_21', 'UNDER_21')], default='UNDER_19', max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('dept', models.CharField(choices=[('LJMCA', 'LJMCA'), ('LJMBA', 'LJMBA')], default='LJMCA', max_length=50)),
            ],
        ),
    ]
