# Generated by Django 4.1 on 2022-10-08 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_playermodel_img1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playermodel',
            old_name='img1',
            new_name='img2',
        ),
    ]
