# Generated by Django 4.1 on 2022-10-16 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_rename_img1_playermodel_img2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playermodel',
            name='img2',
        ),
    ]
