# Generated by Django 4.1 on 2022-09-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0002_contactusermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='evaluationuserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('teamname', models.CharField(max_length=200)),
                ('cfn', models.CharField(max_length=200)),
                ('cln', models.CharField(max_length=200)),
            ],
        ),
    ]
