# Generated by Django 4.1 on 2022-09-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0004_tournamentusermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbackuserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('subject', models.CharField(max_length=200)),
                ('write', models.CharField(max_length=200)),
            ],
        ),
    ]
